export const SET_ONLOADING            = 'SET_ONLOADING'
export const SET_NETWORK_MESSAGE      = 'SET_NETWORK_MESSAGE'
export const GET_REDUCED_URLS         = 'GET_REDUCED_URLS'
export const SET_SHOW_NOTIFY_MODAL    = 'SET_SHOW_NOTIFY_MODAL'

