# Generated by Django 3.2.9 on 2021-11-30 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=400, unique=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('last_visited', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('url_destination', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reducer.domain')),
                ('user_uuid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reducer.users')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'unique_together': {('domain', 'url')},
            },
        ),
    ]
